fix(compartment-mapper)!: Freeze globalThis in each compartment
Agoric/SES-shim pull request #503
Opened 2020-10-24 01:47 UTC by kriskowal

This is the last necessary change to capture in the next release for the bundler in Agoric SDK to work with Compartment Mapper.

2020-10-24 01:53 UTC, warner approved these changes
I'm cool with that, although I don't know who the intended audience of compartment-mapper is. If it's only us for now, great.

Alos, should that be a `harden()` instead of `Object.freeze`? I can't think of strong arguments one way of the other, but it feels like it ought to be a deliberate choice.

2020-10-24 02:14 UTC, kriskowal commented
I believe that freezing is a bette default than harden here, but I defer to @erights. I don’t have strong arguments either way either.

Freezing is sufficient to get Agoric SDK’s bundler to pass the existing tests. It is a likely best practice to harden the `globals` on the way in (Compartment “endowments”).

One advantage of leaving the choice to `harden` to the user is that we don’t need to expose any API to disable the default hardening. We _will_ need to have an API to disable the `freeze`, for packages that depend on mutability of their compartment-isolated globals. Unfortunately, there’s no way to freeze the `globalThis` for every subcontained compartment from the outside—expressing that override in `package.json`s is the way to go.

2020-10-24 02:34 UTC, erights commented
Hi @kriskowal I'm confused about several things in your last message above. Let's chat about it sometime.

2020-10-24 02:34 UTC, erights commented
I added myself as a reviewer.

2020-10-27 04:48 UTC, erights requested changes
Did we agree on `harden` today?

2020-10-27 04:48 UTC, erights commented on packages/compartment-mapper/NEWS.md
> +* *BREAKING*: Every compartment's globals will be frozen unconditionally.
```suggestion
* *BREAKING*: Every compartment's globals will be hardened unconditionally.
```

2020-10-27 04:48 UTC, erights commented on packages/compartment-mapper/src/assemble.js
> +    Object.freeze(compartment.globalThis);
```suggestion
    // TODO harden global conditionally
    harden(compartment.globalThis);
```

2020-10-27 17:24 UTC, closed without merging