Wrap ava test function to log failures to actual console
Agoric/SES-shim pull request #555
Opened 2021-01-01 06:51 UTC by erights

When a test case `test(title, func)` fails because `func` threw an error or returned a promise that eventually rejects, ava prints the stack in what looks like console output but is not. This bypasses all of our fancy error support --- the error details and all the deep stack support -- which made it extremely unpleasant to debug failing tests.

This PR provides a `testWrapper` function that acts like ava's `test` function, except that when a test fails, the failure is also reported to the actual console. When used under SES, this is the fancy console that SES installs.

Since this only does something when the ava test fails, there's no easy way to include an automated test. However I have monkey tested it (in https://github.com/Agoric/agoric-sdk/pull/2159 ) and it seems to work.

2021-01-01 06:57 UTC, erights commented
What else do I need to do so this is pleasantly importable by other tests not in this monorepo?

2021-01-01 07:16 UTC, erights commented
On the monkey testing...

At line 739 of https://github.com/Agoric/agoric-sdk/pull/2159/checks?check_run_id=1632858610#step:7:739 we see

```
REJECTED from ava test: (Error#1)

  Error#1: The trade between left Object <[Object: null prototype] {}> {
    seat: Object <[Object: null prototype] {}> {
      exit: [Function: exit] Function <Function <Complex prototype>>,
      fail: [Function: fail] Function <Function <Complex prototype>>,
      ...
    },
    gains: Object <[Object: null prototype] {}> {
    ...

Error#1 ERROR_NOTE: due to (Error#2)
  Error#1 ERROR_NOTE: Thrown from: (Error#3) : 429 . 2
  Error#1
    Error#2: right element Object <[Object: null prototype] {}> {
      handle: Object <[Object: null prototype] {}> { '@pattern': '*' },
      instance: Object <[Object: null prototype] {}> { '@pattern': '*' },
      installation: Object <[Object: null prototype] {}> {
        getBundle: [Function: getBundle] Function <Function <Complex prototype>>
      },
      description: 'exerciseOption',
      underlyingAssets: Object <[Object: null prototype] {}> {
        UnderlyingAsset: Object <[Object: null prototype] {}> {
          brand: [Alleged: moola brand <Complex prototype> [Alleged: moola brand]],
          value: 3
        }
```
also with deep stack traces

All this is extremely valuable debugging info we weren't seeing despite all our error/console/assert engineering. Hidden by ava.

2021-01-04 23:40 UTC, kriskowal commented
It would be good to see this side-by-side with intended internal usage. I don’t think we want to entrain this in the SES public API. Since this is a mitigation against Ava specifically, we would ideally package this with a name like `ses-ava`. We could do so here and publish it to npm to get it in agoric-sdk.

2021-01-04 23:43 UTC, kriskowal requested changes
To answer your question regarding making this public API, we have options.

Publishing from the SES package would imply some Ava coupling I’d rather avoid.

I’d suggest creating a thing `ses-ava` package in `ses-shim` and publishing it to npm so it can be used in other projects. If we also need to use the test wrapper for our own SES tests, let’s do that in this change, using `ses-ava` as a development dependency.

2021-01-04 23:44 UTC, erights commented
Good plan! Will do.

2021-01-12 16:56 UTC, erights commented
Hi @kriskowal, When you have time, please look at this. I started with your repackage script and tried to adjust from there blindly using other packages for examples. When I `yarn build` I get the following. What have I misconfigured? What needs to be adjusted in repackage.sh ?

```
lerna ERR! npm run build exited 1 in '@agoric/ses-ava'
lerna ERR! npm run build stdout:

> @agoric/ses-ava@0.0.0 build /Users/markmiller/src/ongithub/agoric/SES-shim/packages/ses-ava
> rollup --config rollup.config.js


lerna ERR! npm run build stderr:

src/main.js → dist/ses-ava.mjs, dist/ses-ava.cjs...
[!] Error: 'default' is not exported by node_modules/ava/index.js, imported by src/ses-ava-test.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/ses-ava-test.js (1:7)
1: import test from 'ava';
          ^
2: 
3: const avaTest = test;
Error: 'default' is not exported by node_modules/ava/index.js, imported by src/ses-ava-test.js
    at error (/Users/markmiller/src/ongithub/agoric/SES-shim/packages/compartment-mapper/node_modules/rollup/dist/shared/rollup.js:5265:30)
```

2021-01-12 17:44 UTC, kriskowal reviewed
I believe the error is because Rollup needs a plugin to treat CommonJS dependencies (`ava`) properly. Only packages that have CommonJS dependencies of Rollup artifacts require this plugin. The plugin is already in the dependencies, just was not in the template Rollup configuration.

2021-01-12 17:44 UTC, kriskowal commented on packages/ses-ava/rollup.config.js
> +import { terser } from 'rollup-plugin-terser';
```suggestion
import { terser } from 'rollup-plugin-terser';
import commonjs from '@rollup/plugin-commonjs';
```

2021-01-12 17:44 UTC, kriskowal commented on packages/ses-ava/rollup.config.js
> +    plugins: [resolve()],
```suggestion
    plugins: [resolve(), commonjs()],
```

2021-01-12 17:44 UTC, kriskowal commented on packages/ses-ava/rollup.config.js
> +    plugins: [resolve()],
```suggestion
    plugins: [resolve(), commonjs()],
```

2021-01-12 17:44 UTC, kriskowal commented on packages/ses-ava/rollup.config.js
> +    plugins: [resolve(), terser()],
```suggestion
    plugins: [resolve(), commonjs(), terser()],
```

2021-01-12 18:27 UTC, erights commented
All suggestions applied. Now `yarn build` failing with the following. Just in case I tried doing a `yarn install --force` and tried again and the `yarn build` still fails.

```
lerna ERR! npm run build exited 1 in '@agoric/ses-ava'
lerna ERR! npm run build stdout:

> @agoric/ses-ava@0.0.0 build /Users/markmiller/src/ongithub/agoric/SES-shim/packages/ses-ava
> rollup --config rollup.config.js


lerna ERR! npm run build stderr:

src/main.js → dist/ses-ava.mjs, dist/ses-ava.cjs...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
data:text/javascript, (imported by node_modules/ava/lib/worker/subprocess.js)
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/ava/package.json (2:7)
1: {
2:   "name": "ava",
           ^
3:   "version": "3.15.0",
4:   "description": "Node.js test runner that lets you develop with confidence.",
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (/Users/markmiller/src/ongithub/agoric/SES-shim/packages/compartment-mapper/node_modules/rollup
```

2021-01-28 07:00 UTC, dckc commented on packages/ses-ava/src/types.js
> + * @callback LogCallError
any particular reason to document this type so far away from the implementation? is it re-used somewhere?

2021-02-22 05:33 UTC, erights commented
See #579

2021-03-05 05:08 UTC, erights commented
The state of this PR is that the new source files and test files are all working and ready for review. However...

The first commit is the pristine state resulting from @kriskowal 's `scripts/repackage.sh`. Every change I've made to every one of the files it created, especially `package.json`, I did by cargo culting patterns I saw in other projects without much or any understanding. All those changes should be viewed with great suspicion and are probably wrong. Feel free to replace them in their entirety.

Since the point of this PR is to change what happen when ava reports failure, we can't code this in ava directly as passing tests. To do this correctly, we need #579 which I don't know how to do. Instead, the substantive tests are all commented out of that this package passes CI. If you're inclined to fix this by doing #579 first, that would be great!

@dckc I'm out tomorrow (Friday) but will be back Saturday. Please proceed towards making all these improvements. @kriskowal please help @dckc , especially with the changes I made to the files left behind by `scripts/repackage.sh`.

Thanks!

2021-03-05 05:55 UTC, erights commented
See https://github.com/Agoric/agoric-sdk/pull/2582

2021-03-05 17:25 UTC, dckc approved these changes
I went ahead and fixed any -> unknown.

My other comments are not critical.

2021-03-05 17:26 UTC, dckc commented
@kriskowal please (auto) merge this if you approve it.

2021-03-06 04:23 UTC, kriskowal reviewed
I’ve submitted my feedback in the form of a commit. I fixed the TypeSciprt imports for types.js by removing `import 'ses'` from `types.js`. The evident behavior is that any JS file containing only TS in JSDoc is implicitly imported by all other files in the same directory.

2021-03-06 04:24 UTC, kriskowal approved these changes

2021-03-06 04:25 UTC, merged